project:
  type: website

website:
  title: "MPhil Thesis"
  navbar:
    left:
      - text: "US Data"
        href: us_data.qmd
      - text: "India Data"
        href: india_data.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



