project:
  type: website

website:
  navbar:
    left:
      - text: "US Data"
        href: us_data.qmd
      - text: "India Data"
        href: india_data.qmd
      - text: "Results"
        href: results.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



